apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-journey-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daily-journey
  template:
    metadata:
      labels:
        app: daily-journey
    spec:
      containers:
        - name: daily-journey
          # image: us.gcr.io/my-love-455022/love-daily-journey
          image: 076161/love-daily-journey
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://daily-journey-mongo-srv:27017/daily-journey"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: daily-journey-srv
spec:
  selector:
    app: daily-journey
  ports:
    - name: daily-journey
      protocol: TCP
      port: 4003
      targetPort: 4003
