apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo
  template:
    metadata:
      labels:
        app: photo
    spec:
      containers:
        - name: photo
          # image: us.gcr.io/my-love-455022/love-photo
          image: 076161/love-photo
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://photo-mongo-srv:27017/photo"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: photo-srv
spec:
  selector:
    app: photo
  ports:
    - name: photo
      protocol: TCP
      port: 4002
      targetPort: 4002
