apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeline
  template:
    metadata:
      labels:
        app: timeline
    spec:
      containers:
        - name: timeline
          # image: us.gcr.io/my-love-455022/timeline-service
          image: 076161/timeline-service
          env:
            - name: EMAIL_USER
              value: omery020040@gmail.com
            - name: EMAIL_PASS
              value: wgbehbiaqxlthblt
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: SECRET_KEY
              value: SECRET_KEY
            - name: RESET_PASSWORD_SECRET_KEY
              value: SECRET_KEY
            - name: MONGO_URI
              value: "mongodb://timeline-mongo-srv:27017/timeline"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
          ports:
            - containerPort: 4009
---
apiVersion: v1
kind: Service
metadata:
  name: timeline-srv
spec:
  selector:
    app: timeline
  ports:
    - name: timeline
      protocol: TCP
      port: 4009
      targetPort: 4009
